<?php

namespace App\Http\Controllers\Site;

use App\Comment;
use App\Http\Controllers\Base\BaseController;
use App\Http\Requests\StoreCommentRequest;
use Illuminate\Database\Eloquent\Model;
use Gate;
use Illuminate\Http\Request;

class CommentsController extends BaseController
{
    protected function getModel()
    {
        return new Comment();
    }

    public function createAction(StoreCommentRequest $request)
    {
        return $this->runCreate($request->all());
    }

    public function deleteAction(Request $request, $id)
    {
        $comment = $this->objectManager->findOne($id);
        if (Gate::denies('delete', $comment)) {
            abort(403);
        }

        return parent::deleteAction($request, $id); // TODO: Change the autogenerated stub
    }


}